name: webserver
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.11.3
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - blinker==1.6.2
      - boto3==1.26.135
      - botocore==1.29.135
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cryptography==40.0.2
      - dnspython==2.3.0
      - flask==2.3.2
      - gevent==22.10.2
      - greenlet==2.0.2
      - gunicorn==20.1.0
      - idna==3.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - markupsafe==2.1.2
      - pycparser==2.21
      - pymongo==4.3.3
      - pymongo-auth-aws==1.1.0
      - pymongocrypt==1.6.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - requests==2.30.0
      - s3transfer==0.6.1
      - six==1.16.0
      - urllib3==1.26.15
      - werkzeug==2.3.4
      - zope-event==4.6
      - zope-interface==6.0
